name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    # This references the environment in your GitHub repository settings
    environment: BuildEnv

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker build -t qinbatista/udpserver ./Server \
            --build-arg AWS_KEY="${{ secrets.AWS_KEY }}" \
            --build-arg AWS_SECRET="${{ secrets.AWS_ACCESS }}" \
            --build-arg IPV4_DOMAIN_UPDATE_LAMBDA="${{ vars.IPV4_DOMAIN_UPDATE_LAMBDA }}" \
            --build-arg SERVER_DOMAIN_NAME="${{ vars.SERVER_DOMAIN_NAME }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        run: docker push qinbatista/udpserver